### ISSUE TITLE
Uploading conditional on tag creates new branch on codecov

### ISSUE THREAD

**Issue by spluque** [codecov/codecov-action#101]
How can one upload the report only when tagging a release on a branch?  I'm currently running tests and creating reports on all branches, but want the action to execute only when tagging a release.  This is what I tried:

```yaml
name: Python build

on: [push, pull_request]

jobs:
  build:
    name: Build Python package
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          python -m pip install -r requirements.txt

      - name: Test and coverage
        run: |
          python -m pip install --upgrade coverage
          coverage run -m pytest pkg/tests
          coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if:
          (matrix.python-version == 3.8) &&
          startsWith(github.ref, 'refs/tags')
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
```

Unfortunately, this uploaded a new branch `refs/tags/v*` to codecov.  I had expected the report to end up on the current branch that was checked out in the first step.  Is this not supported, or how can this be done?
