### ISSUE TITLE
gcov_include, gcov_ignore *array* values don't appear to work

### ISSUE THREAD

**Issue by levb** [codecov/codecov-action#1011]
It appears that while single values like `gcov_ignore: examples/**` work fine, any attempt to pass in an array (e.g. `gcov_ignore: 'examples/**,test/**'`) as a string results in passing it directly to the uploader as `-gi 'examples/**,test/**'` as opposed to `-gi 'examples/**' -gi 'test/**'` as its node command line parser requires.

`core.GetInput` does not perform that translation either.

I could just download and invoke the uploader directly, but would prefer to use the action.

(context, I am porting from travis/coveralls to github action, was having issues with coveralls, and decided to try codecov instead. The original travis coveralls command was, `if [[ "$DO_COVERAGE" == "coverage" && "$TRAVIS_COMPILER" == "gcc" ]]; then coveralls --gcov-options '\-lp' -r . -i "src/" -e "src/win/" -e "src/unix/" -e "src/stan/protocol.pb-c.c" -E ".*\.h$"; fi`. I'd like to recreate the functionality).

**Comment by code-schreiber** [comment]
I can confirm that reports still contain ignored stuff although specified not to when using them in a GitHub action
```
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov_ignore: '*foldername*, *._ignored.file'
```

I was trying to avoid having codecov configuration split into 2 different places (GitHub action workflow file and codecov.yml) and would really appreciate this working directly in the GitHub action file.

As a side note, the documentation on how `gcov_ignore` syntax should look like is not available at https://github.com/codecov/codecov-action/

**Comment by thomasrockhu-codecov** [comment]
@levb @code-schreiber sorry for the delay here, we've added support for this in `v5`

**Comment by skirpichev** [comment]
@thomasrockhu-codecov, is this fixed?

I'm trying to add similar config:
```yml
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov_ignore: pythoncapi_compat.h
          gcov_include: '*.c, libzz/*.c'
          gcov_args: --no-external --preserve-paths
          fail_ci_if_error: true
```
in https://app.codecov.io/gh/diofant/python-gmp and it looks like coverage miss file in a sub-directory.
