### ISSUE TITLE
Add support for OIDC instead of token

### ISSUE THREAD

**Issue by MicaelJarniac** [codecov/codecov-action#1016]
PyPI recently did this:
- https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
- https://docs.pypi.org/trusted-publishers/

So now, for publishing a package on PyPI, the author no longer needs to store a PyPI token in the repo's secrets, nor provide it on the GitHub Actions workflow. All they need is to set `permissions.id-token: write` and go to PyPI to authorize this repository and action.

```yaml
permissions:
  id-token: write
steps:
  - uses: pypa/gh-action-pypi-publish@release/v1
```

My suggestion is to support the same for Codecov, where a user no longer needs to worry about tokens, all they need to do is authorize the repository and action on Codecov, and all the authentication is handled automatically with OIDC. An example workflow could look like this:

```yaml
permissions:
  id-token: write
steps:
  - uses: actions/checkout@master
  - run: # Calculate coverage here...
  - uses: codecov/codecov-action@v3
```
