### ISSUE TITLE
No docs on what to pass for `--swift-project`

### ISSUE THREAD

**Issue by dabrahams** [codecov/codecov-action#1037]
Docs don't tell me the meaning of the argument.  Am I expected to pass the name of my Package.swift file, the target name, or what?

Thanks

**Comment by dogo** [comment]
```yml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          swift: true
          swift_project: SWDestinyTrades
          verbose: true    
```
