### ISSUE TITLE
Unexpected input(s) 'yml', valid inputs are ['name', 'token', 'file', 'files', 'directory', 'flags', 'path_to_write_report', 'env_vars', 'fail_ci_if_error']

### ISSUE THREAD

**Issue by tillkruss** [codecov/codecov-action#115]
How can I avoid this warning?

My workflow is:

```yml
  - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: PHP-${{ matrix.php-versions }}-redis-${{ matrix.redis-versions }}-cluster
          yml: ./.github/codecov/codecov.yml
```

codecov.yml:

```yml
codecov:
  require_ci_to_pass: yes
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

```
