### ISSUE TITLE
codecov-action with coverage package

### ISSUE THREAD

**Issue by PrimozGodec** [codecov/codecov-action#116]
I am trying to introduce codecov-action in [our project.](https://github.com/biolab/orange3/pull/4927). We generate report via coverage package:

```
coverage run -m unittest --verbose Orange.tests Orange.widgets.tests
coverage combine
coverage report
```
which produces the report in `.coverage` file. Before we used Travis and we just uploaded the report with `codecov` command. With codecov-action I added the following section to one of the workflows:
```
- name: Upload code coverage
      if: matrix.python == '3.7'
      uses: codecov/codecov-action@v1
      with:
          file: .coverage
```
It seems that it uploads the report but something is wrong with the report and error message does not tell anything: `There was an error processing coverage reports.` Here is the link to the error/report: https://codecov.io/github/biolab/orange3/commit/9f5fea156917ba0772a059771092c9480b387c07

I think that the format of the report file is wrong since in the documentation there is the report in XML format, but I also cannot find how to produce the report in the correct format with `coverage` package.
