### ISSUE TITLE
Upload multiple reports with different flags

### ISSUE THREAD

**Issue by Ekleog-NEAR** [codecov/codecov-action#1176]
Hello!

I’ll start with, this is a duplicate of closed-by-author #243, and of the discussion that happened after #50 was closed.

I’d like to upload multiple reports with different flags. It currently seems to basically require calling the codecov actions multiple times. However, it results in a lot of copy-paste, and workarounds like using `steps: fromJson()` with a custom generator script is even more painful.

Would it be possible to upload multiple reports with different flags? I’m thinking of a syntax like:
```yml
- uses: actions/codecov-action@v??
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    fail_ci_if_error: true
    files:
      - { path: "unit-tests.json", flags: "unit-tests" }
      - { path: "integration-tests.json", flags: "integration-tests" }
```

What do you think?
