### ISSUE TITLE
[v4 upgrade] Config file codecov.yml not found, or is not a file. Ignoring config

### ISSUE THREAD

**Issue by CodeBlanch** [codecov/codecov-action#1242]
Upgrading to v4 I'm getting a warning:

`warning - 2024-01-31 20:00:18,693 -- Config file codecov.yml not found, or is not a file. Ignoring config.`

Our `codecov.yml` currently lives in `./.github/codecov.yml`: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/.github/codecov.yml

Is there a way to pass the correct path? I tried to use `xtra_args` but it doesn't seem to work:

```yml
    - name: Upload code coverage ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
      uses: codecov/codecov-action@v4
      continue-on-error: true # Note: Don't fail for upload failures
      env:
        OS: ${{ matrix.os }}
        TFM: ${{ matrix.version }}
        token: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: TestResults/Cobertura.xml
        env_vars: OS,TFM
        flags: ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
        name: Code Coverage for ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }} on [${{ matrix.os }}.${{ matrix.version }}]
        xtra_args: --codecov-yml-path=./.github/codecov.yml
```

`Warning: Unexpected input(s) 'xtra_args', valid inputs are ['token', 'file', 'files', 'commit_parent', 'directory', 'dry_run', 'env_vars', 'exclude', 'fail_ci_if_error', 'flags', 'name', 'os', 'override_branch', 'override_build', 'override_commit', 'override_pr', 'plugin', 'plugins', 'root_dir', 'slug', 'url', 'verbose', 'version', 'working-directory']`

**Comment by thomasrockhu-codecov** [comment]
@CodeBlanch let me take a look into making a patch for this!

**Comment by thomasrockhu-codecov** [comment]
@CodeBlanch `4.0.1` should allow for this change

It is not ideal, since we should be finding the `codecov.yml` file as you have mentioned. I have opened a ticket [here](https://github.com/codecov/codecov-cli/issues/365).

You should be able to do something like

```yaml
    - name: Upload code coverage ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
      uses: codecov/codecov-action@v4
      continue-on-error: true # Note: Don't fail for upload failures
      env:
        OS: ${{ matrix.os }}
        TFM: ${{ matrix.version }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: TestResults/Cobertura.xml
        codecov_yml_path: .github/codecov.yml
        env_vars: OS,TFM
        flags: ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }}
        name: Code Coverage for ${{ inputs.code-cov-prefix }}-${{ inputs.code-cov-name }} on [${{ matrix.os }}.${{ matrix.version }}]
```
