### ISSUE TITLE
[v4] Failing to import PGP key when updating from v3 to v4

### ISSUE THREAD

**Issue by ryanlambert-wk** [codecov/codecov-action#1279]
After upgrading to v4, the pgp key configured for our code coverage repo cannot be imported. This doesn't stop uploads from succeeding unless you set `fail_ci_if_error: true`

```
Run codecov/codecov-action@v4
==> linux OS detected
https://cli.codecov.io/latest/linux/codecov.SHA256SUM
==> Running version latest
Warning: Codecov: Error importing pgp key
undefined
==> Running version v0.4.6
==> Running command '/runner/_work/_actions/codecov/codecov-action/v4/dist/codecov create-commit'
/runner/_work/_actions/codecov/codecov-action/v4/dist/codecov create-commit -C 084604d6a338b347288b8ff5c1f0bffd229da875
gpg: Signature made Fri Feb  2 14:15:33 2024 UTC
gpg:                using RSA key ...
gpg: Good signature from "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" [unknown]
gpg: WARNING: Using untrusted key!

==> Uploader SHASUM verified
```

**Comment by rohan-at-sentry** [comment]
@thomasrockhu wonder if this is related to https://github.com/codecov/codecov-action/issues/1262

**Comment by thomasrockhu** [comment]
@rohan-at-sentry I don't believe so, this looks like it breaks earlier in the process 

```
Warning: Codecov: Error importing pgp key
```

also the ordering is strange... the `gpg` verification happens before `create-commit` should happen

**Comment by A5rocks** [comment]
Hi, this also happened over at https://github.com/python-trio/trio/actions/runs/7865327122/job/21458126980?pr=2951#step:7:12

At least for us, I suspect this is just because we're running a docker container (https://github.com/python-trio/trio/blob/f071c066b21a745376579313a621b2e15fe363f0/.github/workflows/ci.yml#L186) and things differ from the ubuntu runner. This also messes with the setup-python action.

**Comment by nayunjae** [comment]
Same error with codecov-action@v4
self-hosted / mac os

```
Run codecov/codecov-action@v4.0.1
==> macos OS detected
https://cli.codecov.io/latest/macos/codecov.SHA256SUM
Received SHA256SUM e6d5ac054cba36f5c96176f2f488348f3b55abc74b504f1e348db4a82ff2caa2  codecov
Received SHA256SUM signature -----BEGIN PGP SIGNATURE-----

iQIzBAABCgAdFiEEJwNOf9uFDgu8LGL/gGuyiu[13](https://github.com/wanteddev/android/actions/runs/7968198647/job/21752151639#step:7:14)mGkFAmXOshQACgkQgGuyiu13
mGlaUxAAhb0Z9qjE3cix/Cnzmwb9CgeYoWB76RZ3QktR9Trv5YGqTKlvbWZc0yuF
wGoSrxZcCScWoIoiltIil32ht35rVNgJRaob4nmJu0tLs1c78Cnx6yImgX0PhzgK
LGBPsDCfsgZR1hJpKnc9jhue/NaaqT02pWd+3oMpFmLPRr0reerY29+TDcj35oqG
2X9sxT7Fjt6O59LJLlelaPhdF3wqnc2ygScwy34hzWow3Q0oJ6dscg+DFE7Ra3/Z
q6zXUSqPL[18](https://github.com/wanteddev/android/actions/runs/7968198647/job/21752151639#step:7:19)MEGgxixujgbGAZ72sHdGSBVjOkNmMzJCEsoyWWTVDNj/y9C28SASd
twHl9KVJYhXAv77mHuf/uUrYIW1WnzNe6Y5UJSnI9yDuR+4xcFikIJH2kEs48jV8
zFbB4OsLU+NM80t71+caPbdhcmdGBoBenC+/Kd/0XhpTVxa90gsbFvv43e3uLuKH
Cdp8Gw/scNwWv8r/HkYq+Swkd7wsrpJtNXUxBo+LchI4YCHmUWaN4JVYXmRyaJ4W
Cw8x+Txxc90rW+6nWi+mKM+jqjKD3CO9e4FoE4wv4K9lZMu0BuXs0mz1KE2tUV+e
mHzskMGBCxGbSoX13pKN3OzUpEKfeINboDQ9KOW/XjCx6oagI/pGFfW8La+Qivzd
8nbbpvIdmXDX+SCcYjQ0C4H+LZBI6ZOCw4O+DH0wguVyrHHf9nc=
=Ay4y
-----END PGP SIGNATURE-----

==> Running version latest
Error: Codecov: Error importing pgp key
```

v4 ci script
```
- name: Upload codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: app/build/reports/codeCoverage/app.xml
          verbose: true
          fail_ci_if_error: true
```

Success when using v3
```
   - name: Upload codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: app/build/reports/codeCoverage/app.xml
          verbose: true
          fail_ci_if_error: true
```
