### ISSUE TITLE
[v4] Error importing pgp key in Debian/Ubuntu container

### ISSUE THREAD

**Issue by bdrung** [codecov/codecov-action#1288]
I tried to upgrade codecov-action from v3 to v4, but it fails in the Debian and Ubuntu containers with:
```
Run codecov/codecov-action@v4
/usr/bin/docker exec  e098a5c949955e0c9035a0c5e75133d9ba9232c2f5e1a8ac6aa4681b04b83ca2 sh -c "cat /etc/*release | grep ^ID"
==> linux OS detected
https://cli.codecov.io/latest/linux/codecov.SHA256SUM
Received SHA256SUM 103bfefcc56f76473179e600b96eb8150b0f349ad94836b0f63f03ffac469ad7  codecov
Received SHA256SUM signature -----BEGIN PGP SIGNATURE-----

iQIzBAABCgAdFiEEJwNOf9uFDgu8LGL/gGuyiu13mGkFAmW8+QUACgkQgGuyiu13
mGll6A/8CVDQ3LQaqpgQEIekCJUNKU/+tpF1EGpuUsMi7DZZ0RA6cmazUJFUlZK2
GS7Ptcwly+SYTT+a61SzeVlewPLa47XZIFyC+7tgSO6XgUNlJ+KTevyeL6GG0Qs1
YaciuJv8IHAqaaYT49iKpWE99OME1VXY3fIm4uEHlc4pgnmLv+FNdxnit4AYLGlw
2JHzdDMd5aHlnYYIyYJ9UbM8fFVWgddL1venoYl59NKc5gXjH1/+yPPWz2R+4f22
jZfofI04aEJxNhGinfV5Vykb9asyfMupmLUweArgTIF3wzIEoYo/pK0nVgRBiROE
1hiaH5lti8brA2NF+pzp4+xFEyCU1m/mgN/rj1VRkDs0CW4S86eYWVbfuHEb0ymQ
o7Oe/rST6IjqM72B8eleEdT1DKdeX8DYSXnKvR2J1POyoPMMt/HUoCxphiNOq6Ei
416xOCgqWwOEGbeZ1pxp4Eovf6fffbd2F9MUcJTzgWocOqLh3lZB/EX3G9eLKsyf
WLW3s3NXzajS9j4zEPZxGPmnqAadfm9dzffwokFZnqMTJ7HB4qXH87BPgwPbq8R+
y/1Hv7hHEbJJhbE1fitwHFMg4gfUP6q39VtrfooQSBRYYDzrstowO/L2xsr+AkwW
EQGY70I4SY4XPKKzs8tF3Jch7Oa+xgeNMM1qSGyb2Vjn0KKSDMk=
=jEIQ
-----END PGP SIGNATURE-----

==> Running version latest
Error: Codecov: Error importing pgp key
```
Full log: https://github.com/bdrung/bdebstrap/actions/runs/7876675151/job/21491203247

The codecov action fails and using `verbose: true` does not provide more information. The README does not specify what needs to be installed on the host.

**Comment by thomasrockhu-codecov** [comment]
@bdrung sorry for the wait here. The answer seems to be that `gpg` has not been installed. You can see the failure [here](https://github.com/thomasrockhu-codecov/bdebstrap/actions/runs/8275824138/job/22643404609?pr=1)

I made a PR with some other fixes that were necessary [here](https://github.com/thomasrockhu-codecov/bdebstrap/pull/1). Clearly this wasn't an easy migration, and I'll be taking back some of the learnings here to the product team

cc: @rohan-at-sentry 
**Issues**
1. `gpg` and `gpg-agent` needed to be installed to use the action (this is a result of switching from `opengpg` to `gpg`)
2. the `root` directory could not be found since `git` was not present before `checkout`
3. subsequently `ca-certificates` here could not properly finish the `checkout` stage without being installed prior
4. 2 and 3 are only necessary because the CLI relies on the `git` repository being pulled down. we should remove that dependency if possible

**Comment by bdrung** [comment]
Thanks. Now I am running into the issue that CODECOV_TOKEN is not set correctly and I don't understand why.
```yaml
      - name: debug
        run: >
          echo "CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}" | sed 's/./x/g'
```
shows that the token is set, but the following:
```yaml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
```
has an empty token. See https://github.com/bdrung/bdebstrap/actions/runs/8279831213/job/22655050437

**Comment by drazisil-codecov** [comment]
Hi @bdrung ,

Based on https://github.com/bdrung/bdebstrap/actions/runs/8279831213/job/22655050437#step:10:2, I don't think the token is populating. I think you might be masking `CODECOV_TOKEN: ` instead.

Is the repo secret named `CODECOV_TOKEN` exactly in the settings?

**Comment by drazisil-codecov** [comment]
Hi @bdrung ,

When we say "repo secret" we are referring to under the "secrets and variables" section on the left.

I have a feeling that "environmental secrets" are injected into the workflow differently. I'm not familiar with them, but let me take a look.

**Comment by drazisil-codecov** [comment]
Hi @bdrung ,

Yes, I believe you need to apply the environment in this case, like so https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment

**Comment by drazisil-codecov** [comment]
Hi @bdrung ,

Sounds like it can't find your repo. Please make sure you are running the action after running the checkout step. If your repo is locate in a different location, you may need to pass the `root_dir` key to the action to tell Codecov where to locate your repo files.

**Comment by bdrung** [comment]
The checkout step is the first step and i am not fiddling with the working directory:
```yaml
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: >
          apt-get update &&
          apt-get install --no-install-recommends --yes black isort pylint
          python3 python3-coverage python3-flake8 python3-ruamel.yaml
          shellcheck
      - name: Run unit tests
        run: |
          python3 -m coverage run -m unittest discover -v
          python3 -m coverage xml
      - name: Install dependencies for Codecov
        run: >
          apt-get install --no-install-recommends --yes
          ca-certificates curl git gpg gpg-agent
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
```
