### ISSUE TITLE
Codecov token provided but not found

### ISSUE THREAD

**Issue by dwisiswant0** [codecov/codecov-action#1340]
Just got this error today, never happened before:

```
Error: Codecov token not found. Please provide Codecov token with -t flag.
Error: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

Workflow file:

```yaml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt
          verbose: true
          fail_ci_if_error: true
```

https://github.com/kitabisa/teler-waf/actions/runs/8384025562/workflow#L46-L52
