### ISSUE TITLE
OIDC doesn't work

### ISSUE THREAD

**Issue by nfx** [codecov/codecov-action#1378]
This commit added OIDC - https://github.com/codecov/codecov-action/commit/d820d60619df930d5a859db2d0d77ba93f9d1702 but it doesn't work:

```
error - 2024-04-19 15:53:12,230 -- Upload failed: {"detail":"Github OIDC Token Auth: Invalid token."}
```
and config:
```
permissions:
  id-token: write

jobs:
  ci:
     # ...
      - name: Publish test coverage
        uses: codecov/codecov-action@v4
        with:
          use_oidc: true
```
