### ISSUE TITLE
Feature request: Ability to track binary file size changes

### ISSUE THREAD

**Issue by nmoinvaz** [codecov/codecov-action#1454]
It would be great if codecov action was able to track the changes in compiled binary file size changes between builds. Not only do we want to make sure that certain code was covered by test, we also want to make sure that the changes we've introduced haven't drastically increased the sizes of certain files.

Perhaps something like this:
```
    - name: Publish coverage report
      uses: codecov/codecov-action@v4
      with:
        monitor_file_sizes:
           - myexecutable.exe
```

Then whenever somebody creates a PR on the repository, it would show:
```
myexecutable.exe 201 bytes (+10 bytes)
```
