### ISSUE TITLE
how to enable openid connect with codecov and github actions?

### ISSUE THREAD

**Issue by AndrewAnnex** [codecov/codecov-action#1489]
Currently the readme just links to the github docs page about openid-connect (https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect), but that page nor the readme here or any page I saw in the codecov docs actually _explain step-by-step with commands or urls for pages to access how to enable oidc._ 

Could a more clear step of steps be provided with some sensible default security hardening?

**Comment by jakebailey** [comment]
FWIW all that's needed is to ensure that the `id-token: write` permission is enabled in the workflow; that's it, no other setup needed. Like:

```yaml
jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # ...

      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          use_oidc: true
```

This replaces `${{ secrets.CODECOV_TOKEN }}`. In PRs from forks, `id-token` won't work, but neither would `CODECOV_TOKEN`, so it's equivalent.

(I agree this could be documented better, especially given the answer is basically "just do this one thing and everything magically works"!)
