### ISSUE TITLE
Build and tag Docker image

### ISSUE THREAD

**Issue by localheinz** [codecov/codecov-action#15]
Tried running this action earlier, but using

```yml
steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v1.0.2
  with:
    token: ${{secrets.CODECOV_TOKEN}} #required
    file: ./coverage.xml #optional
    flags: unittests #optional
    name: codecov-umbrella #optional
```

it takes ages to build the Docker image.

What do you think about building and tagging an image, and then pushing it to Dockerhub?

This will significantly speed up actions!
