### ISSUE TITLE
Not valid tokenless upload

### ISSUE THREAD

**Issue by greg0ire** [codecov/codecov-action#1548]
As asked in https://github.com/codecov/codecov-action/issues/1487#issuecomment-2258551527, I'm opening a new ticket.

The failure is still happening for tokenless uploads for `doctrine/dbal`. What's weird is that I've seen it work on one of my own PRs, made from my fork.

## Error message

`error - 2024-08-17 09:46:06,912 -- Report creating failed: {"detail":"Not valid tokenless upload"}`

## Job definition

```yaml
  upload_coverage:
    name: "Upload coverage to Codecov"
    runs-on: "ubuntu-22.04"
    needs:
      - "phpunit-smoke-check"
      - "phpunit-oci8"
      - "phpunit-pdo-oci"
      - "phpunit-postgres"
      - "phpunit-mariadb"
      - "phpunit-mysql"
      - "phpunit-mssql"
      - "phpunit-ibm-db2"


    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2


      - name: "Download coverage files"
        uses: "actions/download-artifact@v4"
        with:
          path: "reports"


      - name: "Display structure of downloaded files"
        run: ls -R
        working-directory: reports


      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v4"
        with:
          directory: reports
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

## Links
- [Failing job](https://github.com/doctrine/dbal/actions/runs/10426300024/job/28890873426?pr=5897)
- [Working job](https://github.com/doctrine/dbal/actions/runs/10405329221/job/28817066100#step:5:129)
- [Job definition](https://github.com/doctrine/dbal/blob/a6707bf8838c112512ac584412766ed576053af2/.github/workflows/continuous-integration.yml#L624-L658)
