### ISSUE TITLE
upload crash with deprecated error [false alarm]

### ISSUE THREAD

**Issue by Borda** [codecov/codecov-action#1570]
it started just an hour ago,
```yaml
  - name: Upload coverage to Codecov
    uses: codecov/codecov-action@v4.5.0
    with:
      token: ${{ secrets.CODECOV_TOKEN }}
      file: ./coverage.xml
      flags: unittests
      env_vars: OS,PYTHON
      name: codecov-umbrella
      fail_ci_if_error: false
```
crashing with 
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
ref: https://github.com/Lightning-AI/utilities/pull/312
