### ISSUE TITLE
Unable to set specific codecov-cli version - SHA256SUM file is not present

### ISSUE THREAD

**Issue by vsarunas** [codecov/codecov-action#1588]
```
==> linux OS detected
https://cli.codecov.io/0.7.4/linux/codecov.SHA256SUM
Received SHA256SUM <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: codecov-cli/listing/0.7.4/linux/codecov.SHA256SUM</Details></Error>
Received SHA256SUM signature <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: codecov-cli/listing/0.7.4/linux/codecov.SHA256SUM.sig</Details></Error>
gpg: key 806BB28AED779869: public key "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
Error: Codecov: Error verifying gpg signature: Command failed: gpg --logger-fd 1 --verify /home/runner/work/_actions/codecov/codecov-action/v4.6.0/dist/codecov.SHA256SUM.sig /home/runner/work/_actions/codecov/codecov-action/v4.6.0/dist/codecov.SHA256SUM
```

**Comment by vsarunas** [comment]
Need to use version with `v` in front:
```
    - name: Upload codecov
      uses: codecov/codecov-action@v4.6.0
      with: 
        #token: ${{ secrets.CODECOV_REPO_TOKEN }}
        version: v0.7.3
        files: info.lcov
        fail_ci_if_error: true
```
