### ISSUE TITLE
"Missing Head Report" but CircleCI passes

### ISSUE THREAD

**Issue by b10n1k** [codecov/codecov-action#1606]
I have sporadic issues on github where the Codecov report is missing[0]. I have checked the circleCI jobs and looks just fine to me[2]. I noticed only that the "Starting create commit process" log line in the "Upload Coverage Results" provides different data than the ones which do not have the problem[1]. 

I read the documentation but I cant say it help me in this case[3]

```{"commit_sha": "b6c7ac4cc198b159179897ac622b46609ccd9c66", "parent_sha": null, "pr": "5944", "branch": "pull/5944", "slug": "os-autoinst/openQA", "token": "0******************", "service": "github", "enterprise_url": null}``` and I dont know why this is happening or if it is the actual issue.

Our codecov.yml 
``` yaml
codecov:
  branch: master
comment:
  behavior: default
  require_changes: true
# https://progress.opensuse.org/issues/88594
fixes:
  - "/home/circleci/openQA::"
coverage:
  status:
    changes: false
    project:
      default:
        target: 98
      tests:
        target: 100.0
        paths:
          - t/
    patch:
      default:
        target: 100.0
        branches: null
```

and in the .circleci/config.yml
``` yaml
version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0
  [....]
  jobs:
  [...]
  codecov:
    docker:
      - <<: *base
    steps:
      - checkout
      - run: *chown_hack_for_cache
      - restore_cache: *restore_cache
      - run: *check_cache
      - store_artifacts: *store_logs
      - run: *install_cached_packages
      - restore_cache: *restore_npm_cache
      - attach_workspace:
          at: .
      - run:
          name: Merge coverage databases
          command: |
            cover -write cover_db cover_db*
            ls cover_db/*cov*
      - run: make coverage-report-html
      - store_artifacts: *store_cover_db
      - run: make coverage-report-codecov
      - run:
          # https://github.com/codecov/codecov-circleci-orb/issues/157
          name: codecov gpg workaround for gpg 2.4 as included in Leap 15.6
          command: mkdir -p ~/.gnupg
      - codecov/upload:
          file: cover_db/codecov.json
          cli_args: -v
```

I dont know where else I can look for to solve this and it is harder considering that this a sporadic incident. Could you assist? Have you seen this before?

[0] https://github.com/os-autoinst/openQA/pull/5944
[1] https://app.codecov.io/github/os-autoinst/openQA/commit/b6c7ac4cc198b159179897ac622b46609ccd9c66
[2] https://app.circleci.com/pipelines/gh/os-autoinst/openQA/14690/workflows/efc4f8d7-1ecd-4c92-8742-ed90ec81f673/jobs/139558
[3] https://docs.codecov.com/docs/error-reference#section-missing-head-commit
