### ISSUE TITLE
Codecov token not found. Please provide Codecov token with -t flag.

### ISSUE THREAD

**Issue by nbari** [codecov/codecov-action#1637]
I keep getting this error:

    Codecov token not found. Please provide Codecov token with -t flag.

https://github.com/s3m/s3m/actions/runs/11792881004/job/32847610066#step:7:35

Either using token or env this always happens:

```
 - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.lcov
          flags: rust
```

or with `token`:

```
- uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          flags: rust
```
