### ISSUE TITLE
Action v5 considers the wrong commit sha

### ISSUE THREAD

**Issue by kristof-mattei** [codecov/codecov-action#1651]
https://github.com/kristof-mattei/logscreen/actions/runs/11849694531/job/33023836063#step:15:145

vs

https://github.com/kristof-mattei/logscreen/actions/runs/11849694531/job/33023837190#step:6:138

Notice that they're part of the same run (see URL).

The invocation is identical:

```
      - name: Upload coverage results (to Codecov.io)
        uses: codecov/codecov-action@968872560f81e7bdde9272853e65f2507c0eca7c # v5
        with:
          disable_search: true
          fail_ci_if_error: true
          files: reports/lcov.info
          flags: back-end
          plugins: noop
          token: ${{ secrets.CODECOV_TOKEN }}
```
and
```
      - name: Upload coverage results (to Codecov.io)
        uses: codecov/codecov-action@968872560f81e7bdde9272853e65f2507c0eca7c # v5
        with:
          disable_search: true
          fail_ci_if_error: true
          files: coverage/vitest/lcov.info
          flags: front-end
          plugins: noop
          token: ${{ secrets.CODECOV_TOKEN }}
```

I do not set the `commit_parent` or `override_commit`.

Yet in the first URL the upload results are uploaded to https://github.com/kristof-mattei/logscreen/commit/cf4fa5e877785cc5a35e385508ed5a72dff95755 which is the hypothetical merge result, not the HEAD of my branch.

@codecov/report-upload
