### ISSUE TITLE
v5 Error: Got unexpected extra argument

### ISSUE THREAD

**Issue by MetRonnie** [codecov/codecov-action#1659]
v5 of the action does not appear to quote the workflow name when calling `./codecov do-upload` so fails if there are spaces in the workflow name: https://github.com/cylc/cylc-flow/actions/runs/11853961703/job/33053084597?pr=6479#step:4:182

**Comment by MetRonnie** [comment]
Tagging @codecov/report-upload as mentioned in https://github.com/codecov/codecov-action/issues/1645

**Comment by thomasrockhu-codecov** [comment]
On it @MetRonnie, thanks for the catch

**Comment by hugovk** [comment]
Similarly: https://github.com/hugovk/pepotron/actions/runs/11860034700/job/33054377932?pr=65#step:8:230

```
Error: Got unexpected extra arguments (Python 3.10)
```
Called like:
```yml
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          flags: ${{ matrix.os }}
          name: ${{ matrix.os }} Python ${{ matrix.python-version }}
 ```
