### ISSUE TITLE
`binary` option does not support absolute paths

### ISSUE THREAD

**Issue by veehaitch** [codecov/codecov-action#1698]
The new `binary` option can currently only work if the given path is relative to the working directory. This happens because the wrapper calls the binary with `./$cc_filename`: https://github.com/codecov/wrapper/blob/588410fe015a58016d5d0546d84fae5cf8242791/dist/codecov.sh#L222

The option should also support absolute paths.

NB: A hack to work around this issue is to create a symlink to the current working directory:

```yaml
- run: ln -s /var/lib/codecov-cli/bin/codecovcli .

- uses: codecov/codecov-action@v5
  with:
    binary: ./codecovcli
    # ...
```
