### ISSUE TITLE
v5.0.7:  URL rejected: Port number was not a decimal number between 0 and 65535

### ISSUE THREAD

**Issue by ssbarnea** [codecov/codecov-action#1711]
Apparently codecov-action code is still... bit shaky, giving:
```
URL rejected: Port number was not a decimal number between 0 and 65535
```

See https://github.com/ansible/ansible-lint/actions/runs/12161810343/job/33917941601?pr=4412#step:8:79

The happened with usage below on a PR coming from a fork:

```yaml
      - name: Upload coverage data
        uses: codecov/codecov-action@v5.0.7
        with:
          name: ${{ matrix.name }}
          # verbose: true # optional (default = false)
          fail_ci_if_error: true
          use_oidc: true # cspell:ignore oidc
```

Under no circumstance this should happen.

I do suspect that adding the magic below might address the failure, I still think that current behaviour is far from desirable UX.

```yaml
use_oidc: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}
```
