### ISSUE TITLE
error importing key with gpg on macOS self-hosted runner

### ISSUE THREAD

**Issue by nmoinvaz** [codecov/codecov-action#1769]
**Describe the bug**
```bash
==> macos OS detected
https://cli.codecov.io/latest/macos/codecov.SHA256SUM
gpg: Note: database_open 134217901 waiting for lock (held by 61669) ...
gpg: Note: database_open 134217901 waiting for lock (held by 61669) ...
gpg: Note: database_open 134217901 waiting for lock (held by 61669) ...
gpg: Note: database_open 134217901 waiting for lock (held by 61669) ...
gpg: Note: database_open 134217901 waiting for lock (held by 61669) ...
gpg: keydb_get_keyblock failed: Value not found
gpg: error writing keyring '[keyboxd]': SQL library used incorrectly
gpg: error reading '/Users/buildbox/Source/actions-runner-2/_work/_actions/codecov/codecov-action/v4/dist/pgp_keys.asc': SQL library used incorrectly
gpg: import from '/Users/buildbox/Source/actions-runner-2/_work/_actions/codecov/codecov-action/v4/dist/pgp_keys.asc' failed: SQL library used incorrectly
gpg: Total number processed: 0
Error: Codecov: Error importing gpg key: Command failed: gpg --logger-fd 1 --no-default-keyring --import /Users/buildbox/Source/actions-runner-2/_work/_actions/codecov/codecov-action/v4/dist/pgp_keys.asc
```

**To Reproduce**
```yaml
    - name: Publish coverage report
      uses: codecov/codecov-action@v4
      if: !cancelled()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.codecov }}
        name: ${{ matrix.name }}
        verbose: false
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
```

**Expected behavior**
Expect it to successfully upload the coverage reports.

**Versions**
 - OS: macos arm64 sequoia 
 - Git Host: GitHub self-hosted runner
 - CI/CD: GitHub actions
 - Uploader: codecov-action@v4

**Additional context**

* There are multiple self-hosted runners on this build box.
* Seems similar to another issue I filed here for Windows: https://github.com/codecov/codecov-action/issues/1377
* I plan to just go back to v3 for all platforms for the time being.
