### ISSUE TITLE
Permission denied error on macOS with v5

### ISSUE THREAD

**Issue by nmoinvaz** [codecov/codecov-action#1771]
**Describe the bug**
Error:
```
codecov-action/v5/dist/codecov.sh: line 252: ./codecov: Permission denied
```
Log:
```bash
Run codecov/codecov-action@v5
Run CC_ACTION_VERSION=$(cat ${GITHUB_ACTION_PATH}/src/version)
==> Running Action version 5.3.1
Run git config --global --add safe.directory /Users/buildbox/Source/actions-runner/_work/client/client
Run CC_FORK="false"
Run if [ "false" == 'true' ] && [ "$CC_FORK" != 'true' ];
==> Token set from env
Run if [ -z "$CC_BRANCH" ] && [ -z "$CC_TOKEN" ] && [ "$CC_FORK" == 'true' ]
Run if [ -z "$CC_SHA" ];
Run ${GITHUB_ACTION_PATH}/dist/codecov.sh
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/
                            Wrapper-0.1.0
                                  
==> Detected macos
 -> Downloading https://cli.codecov.io/latest/macos/codecov
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0 21.9M    0   99k    0     0   447k      0  0:00:50 --:--:--  0:00:50  446k
 47 21.9M   47 10.4M    0     0  8743k      0  0:00:02  0:00:01  0:00:01 8738k
 97 21.9M   97 21.3M    0     0  9845k      0  0:00:02  0:00:02 --:--:-- 9842k
100 21.9M  100 21.9M    0     0  9868k      0  0:00:02  0:00:02 --:--:-- 98[64](https://github.com/snxd/client/actions/runs/13418288950/job/37484513793?pr=2961#step:64:66)k
==> Finishing downloading macos:latest
      Version: v10.0.1
 
==> Bypassing validation...
 -> Token of length 36 detected
==> Running upload-coverage
      ./codecov upload-coverage -t <redacted> --fail-on-error --git-service github --sha 955337de135323eb2166b8a4fef06b6924fdb56f --flag macarm64 --gcov-executable gcov --name Coverage - macOS - Ninja Clang
/Users/buildbox/Source/actions-runner/_work/_actions/codecov/codecov-action/v5/dist/codecov.sh: line 252: ./codecov: Permission denied
```

**To Reproduce**
```yaml
    - name: Publish coverage report
      uses: codecov/codecov-action@v5
      if: always() && !cancelled()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.codecov }}
        name: ${{ matrix.name }}
        verbose: false
        fail_ci_if_error: true
        skip_validation: true
      env:
        CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
```

**Versions**
 - OS: macOS 15 arm64
 - Git Host: GitHub self-hosted runner
 - CI/CD: GitHub Actions
 - Uploader: codecov-action@v5
