### ISSUE TITLE
[BUG] Upload to Codecov Fails Due to Protected Branch Token Requirement

### ISSUE THREAD

**Issue by vicajilau** [codecov/codecov-action#1800]
**Describe the bug**
The upload to Codecov fails with the error: `Token required because branch is protected`. The project is open source and the token is correctly loaded. This issue only occurs with this specific project.

**To Reproduce**
1. Go to the GitHub Actions workflow.
2. Click on the workflow run.
3. Scroll down to the 'Upload coverage reports to Codecov' step.
4. See error.

**Expected behavior**
The coverage report should be uploaded to Codecov without requiring a token for the protected branch.

**Regression**
This issue is a regression. Previous successful instances occurred without requiring a token for the protected branch.

**Screenshots**

**Product Area**
Coverage

**Versions**
- OS: ubuntu-latest
- Git Host: GitHub
- CI/CD: GitHub Actions
- Uploader: codecov-action@v5

**Commit and CI link**
Commit SHA: [Provide the commit SHA]
CI link: https://github.com/vicajilau/file_magic_number/actions/runs/14030383939/job/39298366985

**Additional context**
The YAML file used for the workflow is as follows:

```yaml
name: Dart Analyze + Unit Test

on: push

jobs:
  analyze-unit-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [stable]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: dart analyze

      - name: Run Unit tests
        run: flutter test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: vicajilau/file_magic_number
          fail_ci_if_error: true
          verbose: true
```
