### ISSUE TITLE
[BUG] No "codecov/project" check is run although configured

### ISSUE THREAD

**Issue by polter-rnd** [codecov/codecov-action#1802]
**Describe the bug**

I have the following [.codecov.yml](https://github.com/polter-rnd/slimlog/blob/master/.codecov.yml) which seems to be properly configured to enable both project and patch checks. But neither in master branch nor pull requests I don't see `codecov/project` checks run.

Could you please tell if it's a bug or misconfiguration? Thanks a lot.

**Environment (please complete the following information):**
 - Repo: [slimlog](https://github.com/polter-rnd/slimlog)
 - Example PR: https://github.com/polter-rnd/slimlog/pull/10

I have a matrix strategy set up with different OS and compilers.

For distinguishing between different configuration I use flags. That's how Codecov job is set up for each runner:

```
    - name: Upload coverage reports to Codecov (Linux, MacOS)
      if: runner.os != 'Windows'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.os }}-${{ matrix.c_compiler }}-${{ matrix.format_lib }}
        directory: ${{ steps.strings.outputs.build-output-dir }}/coverage
        fail_ci_if_error: true
```

And finally I manually trigger notifications because those jobs are run in parallel and for some flags there's no coverage (e.g. Windows):

```
    - name: Trigger notifications for Codecov
      if: ${{ !cancelled() }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        run_command: send-notifications
        fail_ci_if_error: true
```

Here's a link to a [full workflow file](https://github.com/polter-rnd/slimlog/blob/master/.github/workflows/cmake-multi-platform.yml).

**Expected behavior**

Both `codecov/project`  and `codecov/patch` checks are run.

**Screenshots**

![Image](https://github.com/user-attachments/assets/77fd9a2b-4d83-409a-8364-fd22f6420f2d)

**Additional Information**

I've already reset the repo and reinstalled the Codecov app, but it didn't help
