### ISSUE TITLE
[BUG] Validate flags argument

### ISSUE THREAD

**Issue by nmoinvaz** [codecov/codecov-action#1805]
**Describe the bug**
We were dynamically generating the flags argument and passing it into `flags:`  on the action.

**To Reproduce**
Use:
```
   - name: Publish coverage report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: $CODECOV
        name: ${{ matrix.name }}
        verbose: false
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
```

**Expected behavior**
It should have some kind of warning if it does not support $ in the `flags` argument,. Instead it makes you think that the report was uploaded successfully and never shows in the UI.

We have since corrected our action to use `${{ env.CODECOV }}` however it was not easy for us to track down.
