### ISSUE TITLE
There was a problem getting the source code from your provider

### ISSUE THREAD

**Issue by guoshiqiufeng** [codecov/codecov-action#1819]
I finished uploading via action and I can see it at `https://app.codecov.io/`, but now I click on the file prompt: `There was a problem getting the source code from your provider. Unable to show line by line coverage.
If you continue to experience this issue, please try logging in again to refresh your credentials.`, What I should do.

[action](https://github.com/guoshiqiufeng/dify-spring-boot-starter/blob/main/.github/workflows/gradle-dify-test.yml)
```
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```

[codecov](https://app.codecov.io/gh/guoshiqiufeng/dify-spring-boot-starter/blob/main/dify-spring-boot-starter%2Fdify%2Fdify-client%2Fdify-client-spring5%2Fsrc%2Fmain%2Fjava%2Fio%2Fgithub%2Fguoshiqiufeng%2Fdify%2Fclient%2Fspring5%2Fbase%2FBaseDifyDefaultClient.java)

github application auth

![Image](https://github.com/user-attachments/assets/7d684933-91bb-4913-b030-bd2a78ded7c3)
