### ISSUE TITLE
`env_vars` input has no visible effect on Codecov UI

### ISSUE THREAD

**Issue by vivodi** [codecov/codecov-action#1828]
According to the README, the `env_vars` input is described as:

> Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)

However, after uploading coverage reports with `env_vars` set, I can’t find these variables reflected anywhere on the Codecov UI. It seems like setting `env_vars` has no effect.

Here is an example coverage report where I configured `env_vars`:
🔗 https://app.codecov.io/github/vivodi/Flexget/commit/ff609bf951cbd68f710a02de2f9dab299f0674fe

```yml
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d  # v5
  with:
    env_vars: OS,PYTHON
    fail_ci_if_error: true
    token: ${{ secrets.CODECOV_TOKEN }}
```

You can find the full GitHub Actions workflow here:
https://github.com/vivodi/Flexget/actions/runs/15089429373/workflow?pr=13
