### ISSUE TITLE
Adjust docs regarding OIDC auth

### ISSUE THREAD

**Issue by rsyring** [codecov/codecov-action#1843]
The docs show the example:

```yaml
permissions:
  id-token: write
```

But that is missing a read permission that would cause the action to be unable to checkout the repo.

It would be better to show a fuller example:

```yaml
permissions:
  contents: read     # For actions/checkout
  id-token: write    # For Codecov OIDC
```

**Comment by rsyring** [comment]
Maybe it's a scoping issue?  The readme has this code snippet:

```
permissions:
  id-token: write
```

And I took that to mean that config should go at the root of workflow.  When I put that at the root I could no longer checkout the repository.

Is it supposed to go on the job or task level instead?

```
- uses: codecov/codecov-action@v5
  with:
    use_oidc: true
    permissions:
      id-token: write
```

Might point still stands though in that it would be helpful to update the readme to show a bit more context for that permissions block.
