### ISSUE TITLE
Just use VM, not docker, to reduce time

### ISSUE THREAD

**Issue by jjangga0214** [codecov/codecov-action#21]
This spends time a LOT (about 90s).

https://github.com/codecov/codecov-action/blob/1c4a4261fac1bbb109d7899828c6ede29ed37f5e/Dockerfile#L8

However, Github VMs already have curl, git and Mercurial preinstalled. Check them out [here](https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts).

So, there is no need to use docker at all. Just run `entrypoint.sh` directly.

**Comment by chetanmeh** [comment]
As a workaround for long time taken directly using the `curl` command also works

```yaml
    - name: Build with Gradle
      env:
        CI: "true"
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        ./gradlew checkScalafmtAll reportTestScoverage
        curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN
```
