### ISSUE TITLE
Unexpected (?) "Please provide upload token from codecov.io with valid arguments

### ISSUE THREAD

**Issue by hakonanes** [codecov/codecov-action#22]
After a few successful uses of this action, I suddenly get the following error message:

```bash
Run codecov/codecov-action@v1.0.2
  with:
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.4/x64
/usr/bin/docker run --name bb81ac7a28060c2a49beacb2ccf7bb13adce_d9298b --label 04bb81 
--workdir /github/workspace --rm -e pythonLocation -e INPUT_TOKEN -e INPUT_NAME -e 
INPUT_FILE -e INPUT_FLAGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e 
GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF 
-e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e 
GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e 
RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v 
"/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp
/_github_workflow":"/github/workflow" -v "/home/runner/work/kikuchipy/kikuchipy":"/github
/workspace" 04bb81:ac7a28060c2a49beacb2ccf7bb13adce  "" "" "" ""
Please provide an upload token from codecov.io with valid arguments
##[error]Docker run failed with exit code 1
```

My .codecov.yml:

```yml
comment:
  layout: "diff, flags, files"
```

and .github/workflows/build.yml unchanged between the successful and unsuccessful action uses:
```yml
name: Build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install Miniconda
        run: |
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          chmod +x miniconda.sh
          ./miniconda.sh -b -p $HOME/miniconda
          hash -r
      - name: Setup environment and install dependencies
        env:
          ENV_NAME: testenv
        run: |
          source $HOME/miniconda/bin/activate root
          conda config --append channels conda-forge
          conda create --name $ENV_NAME --yes
          conda activate $ENV_NAME
          conda info -a
          df -h
          conda install --yes hyperspy pyxem pytest pytest-cov
          pip install .
      - name: Run pytests and generate coverage report
        env:
          ENV_NAME: testenv
        run: |
          source $HOME/miniconda/bin/activate $ENV_NAME
          export MPLBACKEND=Agg
          pytest --cov=kikuchipy --cov-report=xml
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```

The `CODECOV_TOKEN` available via codecov.io is registred in my settings.

I'm sorry if I missed anything obvious. Are anybody able to help me out? Thanks a lot in advance.
