### ISSUE TITLE
All coverage uploads are made towards master

### ISSUE THREAD

**Issue by dumptyd** [codecov/codecov-action#23]
Uploading reports using this action results in the `branch` query parameter being empty and so CodeCov assumes that the commit belongs to `master` (even though it can't find it in the dashboard)

This is causing my badge to show incorrect values because now it's getting affected by coverage reports that are uploaded from other branches.

For now, I've stopped using the action and I'm instead using the bash uploader directly.

```yaml
- name: Upload coverage
      if: success()
      run: bash <(curl -s https://codecov.io/bash) -t $TOKEN -B $REF
      env:
        TOKEN: "${{ secrets.CODECOV_TOKEN }}"
        REF: "${{ github.ref }}"
```
