### ISSUE TITLE
Usage in a monorepo with separate flags for each package

### ISSUE THREAD

**Issue by Devorein** [codecov/codecov-action#243]
Hey there. Thanks for this wonderful gha. I was just wondering what's the best way to use this action for a monorepo. For example, let's say I have package A and B under my monorepo. The way I'm currently using the action is by using multiple `uses` statement like the following:-

```yaml
- uses: codecov/codecov-action@v1
  with:
    files: ./packages/A/coverage/lcov.info
    flags: flag_a
    name: A
- uses: codecov/codecov-action@v1
  with:
    files: ./packages/B/coverage/lcov.info
    flags: flag_b
    name: B
```

I know it's possible to use a comma-separated value to upload multiple files, but I have to set a separate flag for each package, and doing it that way doesn't seem to work.
Thank you.
