### ISSUE TITLE
Environment variables supported or not, which syntax?

### ISSUE THREAD

**Issue by jwillemsen** [codecov/codecov-action#301]
I can't find any reference that environment variables are supported or not, and which syntax to use. For example see the snippets below, I have a `DOC_ROOT` set which I use in multiple places which I also want to use for the `working-directory`. 

```
env:
  DOC_ROOT: ${{ github.workspace }}/ACE_TAO
```

And within the action
```
    - uses: codecov/codecov-action@v1
      with:
        verbose: true # optional (default = false)
        working-directory: $DOC_ROOT
      if: matrix.feature == 'Codecov'
```
