### ISSUE TITLE
Xcode / Swift project - bash script works, github action doesn't find reports

### ISSUE THREAD

**Issue by p4checo** [codecov/codecov-action#306]
Hi 👋🏼 

Tried to use the github aciton on the latest version (`codecov/codecov-action@v1`, `codecov/codecov-action@v1.5.0`), but it fails to find the coverage reports when ran alone. 

However, if I use the classic bash uploader, it then works without an issue.

My suspicion is that the bash uploader is doing some work that the action isn't, because if I run the bash uploader **before** the github action, then the github action successfully finds a report and uploads it.

Useful links:

- [🤖 relevant workflow](https://github.com/Mindera/Alicerce/actions/workflows/ci.yml)
- [✅ bash script only run](https://github.com/Mindera/Alicerce/runs/2531952386?check_suite_focus=true)
- [✅ github action **after** bash script run](https://github.com/Mindera/Alicerce/runs/2536162006?check_suite_focus=true)
- [❌ github action only run](https://github.com/Mindera/Alicerce/runs/2536311210?check_suite_focus=true)

Could you please take a look? Thanks! 🙏🏼

**Comment by p4checo** [comment]
Got it working using `codecov/codecov-action@v3` 🎉 :

```yaml
      - name: codecov upload
        uses: codecov/codecov-action@v3
        with:
          xcode: true
          xcode_archive_path: ${{ env.RESULT_BUNDLE_PATH }}
```
