### ISSUE TITLE
v2 fails to upload coverage

### ISSUE THREAD

**Issue by lwasyl** [codecov/codecov-action#430]
With the upgrade to codecov-action@v2, we see this error when the action attempts to upload the coverage:
```
codecov.io/upload/v4?package=github-action-2.0.1-uploader-0.1.0&token=*******&branch=dependabot/github_actions/codecov/codecov-action-2.0.1&build=***&build_url=*****&commit=****&job=****&pr=***&service=github-actions&slug=****&name=&tag=&flags=&parent=
Error!: Error: Error uploading to https://codecov.io: Error: Error uploading to Codecov: Error: Not Found
```

The action configuration is empty, but we supply the token in `codecov.yml` file under `codecov/token`. This worked well with the codecov-action v1

**Comment by lwasyl** [comment]
@thomasrockhu The issue persists with codecov-action v2.0.2

```
Pinging Codecov: codecov.io/upload/v4?package=github-action-2.0.2-uploader-0.1.0&token=*******&branch=dependabot/github_actions/codecov/codecov-action-2.0.2&build=xxx&build_url=xxx&commit=xxx&job=xxx&pr=xxx&service=github-actions&slug=xxx&name=&tag=&flags=&parent=
Error!: Error: Error uploading to https://codecov.io: Error: Error uploading to Codecov: Error: Not Found
```

`codecov.yml` file:
```yml
codecov:
  token: xxx
  max_report_age: off 
  require_ci_to_pass: false
coverage:
  status:
    project: off
    patch:
      default:
        target: 50%

comment:
  layout: "header, diff, files, footer"
  require_changes: false
  require_base: false
  require_head: true
```

The only difference between this and working version is

```diff
- - uses: codecov/codecov-action@v1
+ - uses: codecov/codecov-action@v2.0.2
```
