### ISSUE TITLE
Can't use codecov action with swift project

### ISSUE THREAD

**Issue by hodovani** [codecov/codecov-action#45]
I can't run codecov report for swift project. The tests are passed in my Xcode 11.3

Here is my GitHub Action workflow:

```
name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build app
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
```

It seems like codecov action try to start python tests here is a log screenshot:

![image](https://user-images.githubusercontent.com/12833067/71591553-74bc9b00-2b35-11ea-9a2f-4992760e63e8.png)
