### ISSUE TITLE
what is report file default value

### ISSUE THREAD

**Issue by sinkcup** [codecov/codecov-action#480]
```
steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v2
  with:
    files: ./coverage1.xml,./coverage2.xml # optional
```

`files` is optional, but I can't find the default value in the docs.

it's `coverage.xml` or `clover.xml`?
