### ISSUE TITLE
Build does not fail with token and invalid input

### ISSUE THREAD

**Issue by ibrahim0814** [codecov/codecov-action#5]
With a given token and an invalid input, the build does not fail and completely disregards the bad input

```yaml
with:
  token: xxxx
  badinput: badstuff
```

The above configuration passes as long as the token is correct
