### ISSUE TITLE
doc: how to use multiple flags

### ISSUE THREAD

**Issue by blueyed** [codecov/codecov-action#50]
The README/doc should have an example how to use multiple flags.
(I've guessed them to be a string separated by "," (commata), as with the codecov-bash uploader itself, but it would be good to clarify)

**Comment by blueyed** [comment]
https://github.com/codecov/codecov-action/blob/66879ff350cce9e19b07c16fd1b227297da67956/action.yml#L15 has examples.

**Comment by ibrahim0814** [comment]
Good point! I've added instructions for how to specify multiple flags in [this commit](https://github.com/codecov/codecov-action/commit/71d5dea6af7ed28ffc892337ef6cc9d63dcfc155)

**Comment by deepankarb** [comment]
It's still not clear how multiple flags will get associated with multiple reports. E.g.:
```
- name: Code coverage (via codecov.io)
      if: matrix.api-level == 29 # Only upload coverage from API 29
      uses: codecov/codecov-action@v2
      with:
        files: engine/build/reports/coverage/debug/report.xml, datacapture/build/reports/coverage/debug/report.xml, datacapturegallery/build/reports/coverage/debug/report.xml
        flags: engine, datacapture, datacapturegallery
        fail_ci_if_error: true
        verbose: true
```

Generates the following:
```
/Users/runner/work/_actions/codecov/codecov-action/v2/dist/codecov -n  -Q github-action-2.1.0 -Z -f engine/build/reports/coverage/debug/report.xml -f  datacapture/build/reports/coverage/debug/report.xml -f  datacapturegallery/build/reports/coverage/debug/report.xml -F engine -F  datacapture -F  datacapturegallery -C <redacted> -v
```

I don't think this is correct.

There should be a way to configure a monorepo with multiple projects / modules, one for each flag.
