### ISSUE TITLE
No coverage files found

### ISSUE THREAD

**Issue by YonatanKra** [codecov/codecov-action#537]
Hi,
I'm running the action like this:
```
with:
    directory: /home/runner/work/vivid-cli/vivid-cli/coverage/
    token: ***
    fail_ci_if_error: true
    files: ./clover.xml
    flags: unittests
    name: codecov-umbrella
```
I'm getting an error: `There was an error running the uploader: No coverage files found, exiting.`

I also tried the `directory` path as `./coverage/` but to no avail.

When I `ls` the `./coverate/` folder, I see the file exists:

```
> ls ./coverage
clover.xml
coverage-final.json
lcov-report
lcov.info
```

Any idea on how to solve this?

**Comment by thomasrockhu** [comment]
@YonatanKra have you tried without specifying `directory` or `files`? Or just `files: coverage/clover.xml`?

**Comment by izelnakri** [comment]
Hi @thomasrockhu I have the same problem. When I do:

```
codecov -f coverage/lcov.info -t $MY_TOKEN
```

it works but this github action:

```yaml
      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: coverage/lcov.info
          flags: js_open_source
          name: memoria
          verbose: true
```

[2021-09-29T12:40:26.420Z] ['error'] There was an error running the uploader: No coverage files found, exiting.


This is very, very disappointing..
