### ISSUE TITLE
Setting threshold

### ISSUE THREAD

**Issue by serialbandicoot** [codecov/codecov-action#554]
I'm trying to set threshold, I've added as below, however it doesn't seem to make any difference. Can you please point me in the direction of the docs.

``` yml
with:
     token: ${{ secrets.CODECOV_TOKEN }}
     files: coverage.xml
     env_vars: OS,PYTHON
     fail_ci_if_error: true
     threshold: 2%
```

**Comment by abhinavsingh** [comment]
We have `codecov.yml` file in repo root, but looks like it is being ignored completely for `threshold`.  CI fails even with `0.01%` of coverage diff.  I am unsure if this is a side-effect of parallel tests on matrix of OS/Python versions.  

Our config file -- https://github.com/abhinavsingh/proxy.py/blob/develop/codecov.yml
Example CI failure which seems to ignore the threshold settings in the config -- https://github.com/abhinavsingh/proxy.py/pull/897

This seemed to work fine with `v1` afaik

**Comment by yaboi** [comment]
Having this same issue... config seems to be ignored but can't add to action...

**Comment by kettanaito** [comment]
The `threshold` option is not supported by the action—it will do nothing:

https://github.com/codecov/codecov-action/blob/e3c560433a6cc60aec8812599b7844a7b4fa0d71/action.yml#L4-L91

I don't see the way to point to the `codecov.yml` file either. 

Can this action determine the root-level `codecov.yml` configuration file? Can we mention this in the README?

**Comment by mataide** [comment]
There no threshold?

**Comment by trajan0x** [comment]
Is there anyway to point to the`codecov.yml` file?

**Comment by arkodg** [comment]
@thomasrockhu-codecov  @mitchell-codecov can you please advise us on how to proceed with this issue ?

**Comment by thomasrockhu-codecov** [comment]
Hi all,

The `codecov.yml` file hold configuration pieces like [threshold](https://docs.codecov.com/docs/commit-status#threshold). At the repository level, it can be named

- `codecov.yml` (preferred)
- `codecov.yaml`
- `.codecov.yml`
- `.codecov.yaml`

and must be directly in one of these directories

- `/` (root)
- 'dev/`
- `.github/`

**Comment by arkodg** [comment]
great thanks for the pointer @thomasrockhu-codecov, this should unblock us. If you gave us some hints on how to enhance the GHA, one of us from the community could help out !

**Comment by noxan** [comment]
After setting threshold the wrong way top level, I saw in the [docs](https://docs.codecov.com/docs/commit-status), that it is a value nested quite deep into their configuration:
```
coverage:
  status:
    project:
      default:
        threshold: 1%
```

Or see the [pull request](https://github.com/ourownstory/neural_prophet/pull/990/files) we used in our project.

**Comment by ethanhanjiahao** [comment]
> Hi all,
> 
> The `codecov.yml` file holds configuration pieces like [threshold](https://docs.codecov.com/docs/commit-status#threshold). At the repository level, it can be named
> 
> * `codecov.yml` (preferred)
> * `codecov.yaml`
> * `.codecov.yml`
> * `.codecov.yaml`
> 
> and must be directly in one of these directories
> 
> * `/` (root)
> * 'dev/`
> * `.github/`

After seeting threshold in .github/codecov.yml, 
```
coverage:
  status:
    project:
      default:
        # basic
        target: 60%
        threshold: 5%
        if_ci_failed: error
```
The same configuration in my repository, it works.  
<img width="835" alt="image" src="https://user-images.githubusercontent.com/10829448/206831714-b09422af-a518-4817-b9ef-e35a3a405f0e.png">

but in remote repository, it not work, CI success. Can you give me some advises or information?
