### ISSUE TITLE
"codecov.sh: line 1: undefined: command not found" on windows-latest

### ISSUE THREAD

**Issue by sajith** [codecov/codecov-action#56]
I have something like this in the configuration, but `secrets.CODECOV_TOKEN` is not configured yet:

```yml
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest

    steps:
      # [test prep, test, etc., steps here]

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
```

Both on `macos-latest` and `ubuntu-latest`, I get an HTTP 400 error, which is fine.  But on `windows-latest`, I get this:

```
Run codecov/codecov-action@v1
  with:
    file: coverage.xml
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\2.7.17\x64
##[warning]Codecov warning: connect ETIMEDOUT 35.199.43.247:443
bash codecov.sh -f coverage.xml -n "" -F "" -y ""
codecov.sh: line 1: undefined: command not found
##[warning]Codecov warning: The process 'bash' failed with exit code 127
```

More [here](https://github.com/sajith/tahoe-lafs/runs/459140414#step:12:1).
