### ISSUE TITLE
v2 shows only Python coverage and omits C coverage

### ISSUE THREAD

**Issue by hugovk** [codecov/codecov-action#566]
Testing switching use of v1 of the action and the bash uploader to v2 of the action means C code which was previously reported is now omitted.

For example, using the action like this (varying the flags/name per OS):

```yml
    - name: Upload coverage
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: ${{ matrix.codecov-flag }}
        name: ${{ matrix.os }} Python ${{ matrix.python-version }}
```

Here's a branch using v1 and the bash uploader, report includes both Python and C code (C code in `src` and `src/libImaging` dirs):

* https://github.com/hugovk/Pillow/tree/main-mingw-coverage-flag
* https://codecov.io/gh/hugovk/Pillow/tree/b522fba4ed58a4449af1c6c788cec15bdb36231d
* https://codecov.io/gh/hugovk/Pillow/tree/b522fba4ed58a4449af1c6c788cec15bdb36231d/src

Here's a branch switching to v2 for both, but report includes only Python code:

* https://github.com/hugovk/Pillow/tree/codecov/codecov-action%40v2
* Diff: https://github.com/hugovk/Pillow/compare/main-mingw-coverage-flag...hugovk:codecov/codecov-action@v2
* https://codecov.io/gh/hugovk/Pillow/tree/ef5e9edfccf5699cbfd0731be52efd4da8f031d3
* https://codecov.io/gh/hugovk/Pillow/tree/ef5e9edfccf5699cbfd0731be52efd4da8f031d3/src

There's a bit of variation between OS, but we're generally building like this:

```sh
CFLAGS="-coverage -Werror=implicit-function-declaration" python3 setup.py build_ext install
```

And testing with `pytest` and `pytest-cov` and generating `coverage.xml` with either the `--cov-report xml` switch or `coverage xml` command.

Am I missing something?
