### ISSUE TITLE
v2 Error: Expected a string but received a Array

### ISSUE THREAD

**Issue by thangleiter** [codecov/codecov-action#571]
Today I experienced the same problem as https://github.com/codecov/codecov-action/issues/561, however, migrating from v1 to v2 did not help me. Instead, I get [a new error](https://github.com/qutech/filter_functions/runs/3998713843?check_suite_focus=true#step:6:43) with the uploader exiting with code 255:
```
[2021-10-25T17:54:04.067Z] ['verbose'] The error stack is: TypeError: Expected a string but received a Array
    at assertString (/snapshot/repo/node_modules/validator/lib/util/assertString.js:17:11)
    at Object.isAlphanumeric (/snapshot/repo/node_modules/validator/lib/isAlphanumeric.js:18:29)
    at validateToken (/snapshot/repo/dist/src/helpers/validate.js)
    at getToken (/snapshot/repo/dist/src/helpers/token.js)
    at main (/snapshot/repo/dist/src/index.js)
    at Object.<anonymous> (/snapshot/repo/dist/bin/codecov.js)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[2021-10-25T17:54:04.067Z] ['verbose'] End of uploader: 13 milliseconds
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v2/dist/codecov' failed with exit code 255
```

The codecov block in my `yaml` looks like this:
```yaml
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v2
  with:
    file: ./coverage.xml
    name: ${{ matrix.python }} - ${{ matrix.install_extras }}
    env_vars: OS,PYTHON
    fail_ci_if_error: true
    verbose: true
```

**Comment by BeyondEvil** [comment]
I have this error as well.

```yml
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        file: ./coverage.xml
        flags: tests
        name: ${{ matrix.py }} - ${{ matrix.os }}
        verbose: true
```
