### ISSUE TITLE
400 error on uploading to Codecov

### ISSUE THREAD

**Issue by alexgleith** [codecov/codecov-action#58]
I've experienced a few errors with the following message:

```
Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200214-585fef0&token=secret&branch=refs%2Fpull%2F105%2Fmerge&commit=65f5df278779f85ec4951d271f741ea963000f26&build=&build_url=http%3A%2F%2Fgithub.com%2Fopendatacube%2Fdatacube-explorer%2Factions%2Fruns%2F&name=&tag=&slug=opendatacube%2Fdatacube-explorer&service=github-actions&flags=&pr=&job=
HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
```

I'm configuring the action like this:
```
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CodeCovToken }}
        file: ./coverage.xml
        fail_ci_if_error: false
```

And it works _most of the time_, as in, almost always. Just fails occassionally.
