### ISSUE TITLE
Error: "Please provide an upload token from codecov.io with valid arguments" on public repo

### ISSUE THREAD

**Issue by GuyARoss** [codecov/codecov-action#687]
I have been following your V2 uploader guide and received the following error in the header.

This is what my yaml workflow looks like:
```yml
name: codecov
on: [push]
jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Generate coverage report
        run: |
          go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
    
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella

```

I also noticed in your example the following line is stated
```yml
 token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
```

So I tried running this same task with and without the `CODECOV_TOKEN`, to which they both yield the same result.

Is this a bug? or a failure of competency on my part?
