### ISSUE TITLE
Failed uploading reports to CodeCov (400: pr must match pattern)

### ISSUE THREAD

**Issue by TomerFi** [codecov/codecov-action#69]
Hello

I'm trying to upload coverage reports to `CodeCov` and it doesn't work most of the time.

This is my configuration:
```yaml
      - name: Push coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./coverage_report/coverage.xml
          fail_ci_if_error: true
```

Up until 7 days ago, it worked, as far as I can tell, perfectly.
Ever since then the action worked well just once, about 4 hours ago.

For most of the times, after a couple of tries, the action gets a `400` response code with the following error:
```
pr must match pattern ^(\d+|false|null|undefined|true)$
```

I've tried setting the action version to the fixed major syntax `codecov/codecov-action@v1`,
but the same result was accepted.

[CodeCov project](https://codecov.io/gh/TomerFi/aioswitcher).
[GitHub project](https://github.com/TomerFi/aioswitcher/blob/dev/.github/workflows/build.yml#L70)

Please,
any advice?

**Comment by nvengal** [comment]
Looks like this is related to a change on githubs end.
The `GITHUB_REF` is expected to be in the format  `refs/pull/#/merge`.
From https://codecov.io/bash
```
# PR refs are in the format: refs/pull/7/merge
pr="${GITHUB_REF#refs/pull/}"
pr="${pr%/merge}"
```

Looks like at some point github changed the format.
From https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
```
GITHUB_REF | The branch or tag ref that triggered the workflow. For example, refs/heads/feature-branch-1. If neither a branch or tag is available for the event type, the variable will not exist.
```

**Comment by TomerFi** [comment]
Thanks @nvengal .

It's weird, I have another repository doing the same upload and it works pretty well...

**Comment by mrcasals** [comment]
We've noticed something similar on https://github.com/decidim/decidim. We've noticed that, on `pull_request` event, if the workflow fails for a random issue and then we rerun the job, this new job consistently fails to upload the coverage with the error reported in the description of this issue. Is this happening to you too @TomerFi?

For more details, considering a PR with ID 1 from `my-branch` to `master`:

- On the first run, `GITHUB_REF=refs/pull/1/merge`. This value makes the `checkout` action to checkeout this weird branch, and Codecov uses the head of this branch as reference to push the coverage
- Once the job fails and we rerun it, we have `GITHUB_REF=refs/heads/my-branch`. The `checkout` actions checks out to this branch now, and when trying to push it uses its head, which is different from the first run. 

This last behavior is the same we get when running jobs with the `push` event, so the solution could be to only use `push` events, but `push` events are not fired from forks, so then we'd miss the runs for those PRs.

**Comment by TomerFi** [comment]
I'm not sure this is the same behaviour,
although it quite possibly is the same reason.

I can't find any pattern for cases where the upload fails,
It happens from both forks and local branches.

I'll look into the ref value as well,
I'll verify whether or not we have the same symptoms.

**Comment by mrcasals** [comment]
We've replaced the action with a custom step, here's the PR in case it helps debugging: https://github.com/decidim/decidim/pull/5991

**Comment by TomerFi** [comment]
@mrcasals Thank you!

**Comment by nschloe** [comment]
Same issue here. Too bad that this seems to be so difficult to deal with. I've now replaced
```yaml
    - name: Submit to codecov
      uses: codecov/codecov-action@v1
      with:
        flags: ${{ matrix.python-version }}
```
with
```yaml
    - name: Submit to codecov
      if: success()
      run: |
        curl -s https://codecov.io/bash -o codecov.sh
        bash codecov.sh -F ${{ matrix.codecov-flag }}
      env:
        CODECOV_NAME: ${{ matrix.os }} Python ${{ matrix.python-version }}
```
