### ISSUE TITLE
Is it a way to scan report files for upload?

### ISSUE THREAD

**Issue by mayuanyang** [codecov/codecov-action#727]
I am using dotnet to generate report files in `coverage`, a sub folder with the naming rule of GUID is created  for each `dotnet version` run, looks like codecov-action does not auto detect the sub folders and their files, so is it a way to scan them and upload?

My settings
```
 - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/
          verbose: true
```

Here is the folder structure
![image](https://user-images.githubusercontent.com/3387099/167509199-645a43cc-4fdd-429b-8e8e-e8caf936f6bb.png)

Thanks
