### ISSUE TITLE
How to see detailed coverage report in each pull request

### ISSUE THREAD

**Issue by ayushmishra2005** [codecov/codecov-action#738]
Here is my `coverage.yml` configuration. 

```
name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        rust: [ nightly ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install wasm32-unknown-unknown
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: wasm32-unknown-unknown
          override: true

      - uses: actions-rs/install@v0.1.2
        with:
          crate: cargo-tarpaulin
          version: 0.20.0
          use-tool-cache: true

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --no-fail-fast --all-features --line -p pallet-template --timeout 300 --out Xml
      - name: Upload To Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
          verbose: true
 ```
 
 I want to see a detailed report in my PR. But I can see only limited reports in my PR like the below screen
 
 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/1575561/169224472-16a76760-4369-4fb8-a49d-abb85e902e4d.png">

I can see a detailed report after login in to https://app.codecov.io/. How can I see a detailed report in my PR, like line-wise, file wise etc?
