### ISSUE TITLE
Unexpected input 'env_vars'

### ISSUE THREAD

**Issue by leezu** [codecov/codecov-action#80]
```
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,PYTHON
```

triggers warning `Unexpected input 'env_vars', valid inputs are ['name', 'token', 'file', 'flags', 'fail_ci_if_error']` despite following the example of https://github.com/codecov/codecov-action#arguments

**Comment by TsumiNa** [comment]
have same warning

**Comment by thuitaw** [comment]
Got the same error here
```
##[warning]Unexpected input 'env_vars', valid inputs are ['name', 'token', 'file', 'flags', 'fail_ci_if_error']
Run codecov/codecov-action@v1
  with:
    token: ***
    file: ./coverage.xml
    flags: unittests
    env_vars: OS,PYTHON
    name: codecov-umbrella
    fail_ci_if_error: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.10/x64
bash codecov.sh -f ./coverage.xml -n codecov-umbrella -F unittests -Z
```

**Comment by pmeier** [comment]
`env_vars` was only introduced by [`v0.1.7`](https://github.com/codecov/codecov-action/releases/tag/v1.0.7). You could pin the version in the workflow:

```yml
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v1.0.7
  with:
    env_vars: OS,PYTHON
```
