### ISSUE TITLE
Coverage report is not uploading

### ISSUE THREAD

**Issue by eftalgezer** [codecov/codecov-action#830]
I get the error:
```
[2022-09-19T10:59:31.265Z] ['error'] None of the following appear to exist as files: /home/runner/work/SIESTAstepper/SIESTAstepper/coverage.xml
[2022-09-19T10:59:31.266Z] ['error'] There was an error running the uploader: Error while cleaning paths. No paths matched existing files!
```
https://github.com/eftalgezer/SIESTAstepper/actions/runs/3081846214/jobs/4980851248

My file is:

```
- name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        files: /home/runner/work/SIESTAstepper/SIESTAstepper/coverage.xml
        flags: unittests
```
https://github.com/eftalgezer/SIESTAstepper/blob/main/.github/workflows/python-package.yml
