### ISSUE TITLE
Using this action causes my workflow to be queued forever

### ISSUE THREAD

**Issue by tamj0rd2** [codecov/codecov-action#86]
Here's my ci.yml

```
name: CI

on:
  push:
    branches: [master, next, next-major, beta, alpha]
  pull_request:
    branches: [master, next, next-major, beta, alpha]
  schedule:
    - cron: "0 9 * * *"

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build deps
        run: docker-compose build release

      - name: Linting
        run: docker-compose run lint
      - name: Typecheck
        run: docker-compose run typecheck
      - name: Tests
        run: docker-compose run cover
      - name: Copy coverage reports
        run: docker cp $(docker-compose ps -qa cover):/usr/src/app/coverage ./coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

      - name: Release
        if: ${{ github.event_name != 'pull_request' }}
        run: docker-compose run release
        env:
          GITHUB_TOKEN: ${{ secrets.NCDC_GITHUB_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

This workflow was queued for 20 minutes until I had to cancel it. However, removing the "Upload Coverage" step got it to work again immediately. Have I got a strange syntax error here/am I using this wrong?

![image](https://user-images.githubusercontent.com/20561445/86158131-42015880-bb00-11ea-8f91-1720a15c448a.png)
