### ISSUE TITLE
Action hangs at ['info'] Running xcode coversion... for a very long time

### ISSUE THREAD

**Issue by BrentMifsud** [codecov/codecov-action#921]
Running this action for Xcode projects takes 20 min or so.

It seems to be hanging at this step:
```
[2023-02-17T07:22:38.486Z] ['info'] Running xcode coversion...
[2023-02-17T07:42:10.036Z] ['info'] Searching for coverage files...
```

my workflow step looks like this:

```
- name: Codecov Reporter
  uses: codecov/codecov-action@v3.1.1
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    xcode: true
    xcode_archive_path: '.build/test-results/MyScheme.xcresult'
```

Another thing to note, is that this does not seem to be dependant on the size of the .xcresults file. It has taken 20 min with a 6 mb file, and also with a massive 200mb one.
