### ISSUE TITLE
[Bug] Commit status check missing when action is triggered by pull_request event

### ISSUE THREAD

**Issue by sfdye** [codecov/codecov-action#95]
We noticed the commit status check started to disappear once we migrate from Travis CI to Github Action (using this action for uploading coverage to codecov)

Further debugging reveals that with
```yaml
on:
  push:
    branches: master
  pull_request:
```
there is no status check.

However if the event trigger is `push`

```yaml
on:
  push:
  pull_request:
```

the status check is back.
