### ISSUE TITLE
Specify Swift packages for code coverage

### ISSUE THREAD

**Issue by adamhaafiz** [codecov/codecov-action#998]
In the deprecated [Bash Uploader](https://docs.codecov.com/docs/about-the-codecov-bash-uploader) there is an option to specify which Swift packages should be included via `-J {package name}` argument. I tried to replicate this using the `xtra_args` but was not successful:

```
uses: codecov/codecov-action@v3
with:
  swift: true
  xtra_args: -J {package name}
```

Is this feature available in this uploader? If so, how?
